const GAME_WIDTH = 960;
const GAME_HEIGHT = 540;
const TOTAL_TIME_MS = 90000;
const MAX_LEADERBOARD = 10;
const MAX_NICKNAME_LEN = 4;
const LEADERBOARD_KEY = 'family_relay_leaderboard';
const BALL_RADIUS = 12;
const PLAYER_SIZE = 28;
const PLAYER_SPEED = 200;
const BALL_FRICTION = 0.97;
const BALL_KICK_FORCE = 280;
const PASS_RELAY_DWELL_MS = 500;
const TRANSITION_DURATION_MS = 1500;

export {
  GAME_WIDTH,
  GAME_HEIGHT,
  TOTAL_TIME_MS,
  MAX_LEADERBOARD,
  MAX_NICKNAME_LEN,
  LEADERBOARD_KEY,
  BALL_RADIUS,
  PLAYER_SIZE,
  PLAYER_SPEED,
  BALL_FRICTION,
  BALL_KICK_FORCE,
  PASS_RELAY_DWELL_MS,
  TRANSITION_DURATION_MS,
};
